name: Build Docker image

on:
  push:
    branches:
      - master
    paths:
      - 'requirements.txt'
      - 'anon/*'
      - '.github/workflows/docker.yaml'
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: set_version
        run: |
          echo "VERSION=v$(cat anon/common.py | grep VERSION | cut -d '=' -f2 | tr -d \' | tr -d ' ')" > $GITHUB_ENV
          echo "Current VERSION=${{ env.VERSION }}"

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/anon:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/anon:${{ env.VERSION }}
            ghcr.io/${{ github.actor }}/anon:latest
            ghcr.io/${{ github.actor }}/anon:${{ env.VERSION }}
